# Generated by Django 5.0.6 on 2024-07-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_menureview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodcriticrestaurantreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='menureview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='regularrestaurantreview',
            unique_together=set(),
        ),
    ]
