# Generated by Django 5.0.6 on 2024-07-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_zoodisplayanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='availability',
            field=models.BooleanField(choices=[('Available', True), ('Not Available', False)], default=True),
        ),
    ]
