# Generated by Django 5.0.4 on 2024-06-17 12:25

from django.db import migrations
from main_app.models import Shoe


def add_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    unique_brands_names = shoe.objects.values_list('brand', flat=True).distinct()

    for brand_name in unique_brands_names:
        unique_brands.create(brand_name=brand_name)


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(add_unique_brands)
    ]
